### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by Idicious** [kwolfy/webworker-promise#10]
First of all I would like to thank you for this lovely library, it, together with the webpack 5 worker loader is the first time I've felt working with web workers to be a good dev experience.

I took the liberty  of creating some Typescript definitions for the project, and I would like to submit them to the DefinitelyTyped repository so that they will be automatically included for anyone who installs the package. Here is the PR: https://github.com/Idicious/DefinitelyTyped/pull/1. I'd first like your input on the matter before officially submitting it.

Alternatively I could actually open up a PR in this repo and add the TS definitions directly here. Doing either of these will provide autocompletion + docs in most editors.

**Comment by kwolfy** [comment]
Hi, sorry for delay. Thank you, send PR please

**Comment by Idicious** [comment]
Just for clarity, would you prefer me to add them into this repo, or to open a PR to DefinatelyTyped with them?

**Comment by kwolfy** [comment]
> Just for clarity, would you prefer me to add them into this repo, or to open a PR to DefinatelyTyped with them?

I would happy to see in this repo

**Comment by Debdut** [comment]
I don't see the TS definitions yet! What's the status?

**Comment by Idicious** [comment]
I apologize, this slipped my mind a bit. I'll see if I have some time this week to open a PR.

**Comment by Debdut** [comment]
Awesome looking forward 🤩

**Comment by Debdut** [comment]
Thank you so much!
