### ISSUE TITLE
Prototype Inheritance (Tiny Emitter)

### ISSUE THREAD

**Issue by Gabisampaio** [kwolfy/webworker-promise#12]
#### Bug Description
If the `eventName` is in the set of properties defined in Object.prototype (`constructor`, `hasOwnProperty`, `isPrototypeOf`, `propertyIsEnumerable`, `toLocaleString`, `toString`, `valueOf`), there would be a TypeError on [this line](https://github.com/kwolfy/webworker-promise/blob/366eeb8a805745b82cb17a047df4ef69cd4f5b9d/src/tiny-emitter.js#L34).

This happens because, in JavaScript, objects inherit from Object.prototype by default. This can create potential issues that, although may be unlikely to happen, still represent a risk. 

#### Fix 
One of the possible fixes for this is creating the object without enabling prototype inheritance. More specifically, this would affect the `__listeners` property defined in `TinyEmitter`. Applying the fix suggested below makes the application not to crash even if the `eventName` is a string in the set of properties listed above.

--- TinyEmitter constructor (original) ---
```
class TinyEmitter {
  constructor() {
    Object.defineProperty(this, '__listeners', {
      value: {},
      ...
    });
  }
...
}
```

--- Tiny Emitter constructor (fixed) ---
```
class TinyEmitter {
  constructor() {
    Object.defineProperty(this, '__listeners', {
      value: Object.create(null),
      ...
    });
  }
...
}
```

**Comment by kwolfy** [comment]
Thank you. 

This is a very important note. I will fix
