### ISSUE TITLE
Worker pool: `maxThreads` and `maxConcurrency` validation

### ISSUE THREAD

**Issue by Gabisampaio** [kwolfy/webworker-promise#13]
#### Current behaviour
There is currently no validation for the `maxThreads` and `maxConcurrentPerWorker` parameters in the Worker pool. This raises to inconsistencies, such as: 
* A worker being created even if `maxThreads` is 0
* `maxThreads` or `maxConcurrency` being assigned floating point values. If this happens, certain properties are not met. For instance, we could have `maxThreads` assigned to `2.5` and `3` workers created. This means that, for these particular cases, the actual number of threads could be **greater** than `maxThreads`. Maybe it would make sense to forbid this by requiring both `maxThreads` and `maxConcurrentPerWorker` to be integers greater or equal to `1`.

#### Possible fix
--- WorkerPool Constructor (Original) ---
```
class WorkerPool {
  constructor({create, maxThreads, terminateAfterDelay, maxConcurrentPerWorker}) {
    ...
    this._maxThreads = maxThreads;
    ...
    this._maxConcurrentPerWorker = maxConcurrentPerWorker;
    ...
  }
...
}
```

--- WorkerPool Constructor (Fixed) ---
```
class WorkerPool {
  constructor({create, maxThreads, terminateAfterDelay, maxConcurrentPerWorker}) {
    ...
    if(!Number.isInteger(maxThreads) || !Number.isInteger(maxConcurrentPerWorker) || maxThreads < 1 || maxConcurrentPerWorker < 1){
       throw new TypeError('Expected maxThreads and maxConcurrentPerWorker to be integers greater or equal to 1');
    }
    this._maxThreads = maxThreads;
    ...
    this._maxConcurrentPerWorker = maxConcurrentPerWorker;
    ...
  }
...
}
```

**Comment by kwolfy** [comment]
I agree with you. But i would like to use warnings instead of TypeError cause many people already use library and may get TypeError that will broke application.

I would like to see PR if you interested.

Thank you.

**Comment by Gabisampaio** [comment]
Thanks for the feedback. I will submit a PR :-)
