### ISSUE TITLE
Please publish new build (0.5.0) to NPM

### ISSUE THREAD

**Issue by flakey-bit** [kwolfy/webworker-promise#17]
Hey!

Thanks for the great package. I was eagerly awaiting throwing away my custom typings, but noted that 0.5.0 isn't published to NPM yet (latest is 0.4.4)

![image](https://user-images.githubusercontent.com/4413825/157135352-fa7ca015-d992-4b95-9ae4-7347c8c45e8d.png)

Cheers,
Eddie

**Comment by kwolfy** [comment]
Sorry for that. Done. Thanks
