### ISSUE TITLE
Typescript types not correctly published to npm

### ISSUE THREAD

**Issue by Idicious** [kwolfy/webworker-promise#18]
I noticed that the version with typescript types is published to npm, but the type files haven't been copied from the `src` to `lib` directory, which is the type root. Copying the type files is part of the prepublish script in the repo, but perhaps you use another command in the ci tooling.

In any case, to fix this, before publishing to npm the prepublish script should be run.

**Comment by mesfahanisimscale** [comment]
@kwolfy can you please republish the npm package after `npm run prepublish` so that the types are included in the `/lib` folder? It'd be very much appreciated!

**Comment by kwolfy** [comment]
Sorry for delay. Now i published them
