### ISSUE TITLE
'Promise' is undefined in IE11

### ISSUE THREAD

**Issue by jwmann** [kwolfy/webworker-promise#4]
So I'm aware that IE11 doesn't support ES6 and therefore Promises.
I'm using webpack's `worker-loader` to require all my libraries I need and I'm passing the workers through`babel-loader` so I can write in ES6.

I was using `promise-worker` prior to this but I didn't like that it JSONifies my data without any options and I found your library through an issue.

Unfortunately in your register.js file you return a new Promise and IE11 is not happy about it.
`promise-worker` doesn't seem to have this problem and works fine in IE11

Is there something we can do to add this compatibility?

**Comment by jwmann** [comment]
I fixed it by adding:
````
require('babel-polyfill');
````
To the top of my worker.js but it would be nice if it worked as well as `promise-worker` does.

**Comment by kwolfy** [comment]
Thanks for report, i will fix it soon

**Comment by kwolfy** [comment]
I removed promise using in register js, so now - it is not required
