### ISSUE TITLE
Promise.all example

### ISSUE THREAD

**Issue by thewtex** [kwolfy/webworker-promise#5]
Hi there,

Thanks for maintaining this project!

I am spawning many workers and trying to collect them with `Promise.all`, but the return value is not expected. Is there an example I could look at to use `webworker-promise` with `Promise.all`?

Thanks,
Matt

**Comment by thewtex** [comment]
Nevermind, this was an error on my part.

**Comment by kwolfy** [comment]
@thewtex Yes, `Promise.all` returns just normal promise, so, you can just return Promise.all(...) as usual
