### ISSUE TITLE
how to send message from worker to main process at any time?

### ISSUE THREAD

**Issue by pdwrl** [kwolfy/webworker-promise#6]

**Comment by kwolfy** [comment]
You can use built-in event-emitter

https://github.com/kwolfy/webworker-promise#eventemitter

**Comment by pdwrl** [comment]
`worker.emit('add', 11, 22);`
As I see, main process initiates this exchange of messages, not worker...
But could You please tell me how does worker may emit message to main process without any request/message from main proc.?

**Comment by pdwrl** [comment]
postMessage() or self.postMessage() from worker throws an error
> Uncaught Error: Wrong message type 'P'
>     at Worker._onMessage (index.js?8455:142)

**Comment by kwolfy** [comment]
@mgfck3 from worker you can use similar method - `host.emit('add:ok', 42)`

**Comment by pdwrl** [comment]
> 
> 
> @mgfck3 from worker you can use similar method - `host.emit('add:ok', 42)`

throws an error:

> tiny-emitter.js?8590:30 Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
>     at Worker.emit (tiny-emitter.js?8590:30)
>     at Worker._onMessage (index.js?8455:135)

**Comment by kwolfy** [comment]
You should update webworker-promise to the latest (0.4.2)

**Comment by pdwrl** [comment]
Yes, problem with error solved, thank You.
But how to catch message from worker?
```
// main.js
W.onmessage = function(e){
	console.log(e)
}
```
This code catches data but no one promise resolves anymore with "webworker-promise"

**Comment by kwolfy** [comment]
Well, you should use it as regular event-emitter. Listen in `worker.on('event', cb)`, and send in `host.emit('event')`
Please read doc one more time [here](https://github.com/kwolfy/webworker-promise#eventemitter)

**Comment by pdwrl** [comment]
kwolfy, thank You very much for Your support!
Everything works.
