### ISSUE TITLE
use websocket in webworker-promise

### ISSUE THREAD

**Issue by liyunfei18** [kwolfy/webworker-promise#8]
Hi，First of all thank you for your contribution to this project! I used websocket in webworker-promise to fetch some files, and I hoped that main.js use postMessage to send some files name to woker.js and then main.js can get files in .then() from the worker. But a problem occurred: If I send file A name first, and then send file B name, file B arrives before file A during the socket acquisition process, then I can only get file B in .then() of the main thread (File A in the worker will be received after B is received, but File A will not be sent to main.js by the worker). This sounds a bit messy, here is part of my code：
worker.js
`import registerWebworker from 'webworker-promise/lib/register';
let ws;
registerWebworker(async function (wwMessage, emit) {
    return new Promise((resolve, reject) => {

        if (wwMessage.init) {
            console.log('Creating socket');
            ws = new WebSocket('ws://localhost:8888/');
            ws.binaryType = 'arraybuffer';
            ws.onopen = function () {
                console.log('Socket open.');
            }
        }

        ws.onclose = function () {
            console.log('Socket close.');
        }

        ws.onerror = function (event) {
            console.error("WebSocket error observed:", event);
        };

        if (wwMessage.data) {
            console.log("Client socket message:", wwMessage.data);
            let wsMessage = JSON.stringify(wwMessage.data);
            ws.send(wsMessage);
        }

        ws.onmessage = function (wsMessage) {
            let arrayBuffer = wsMessage.data;
            console.log('Socket server message', arrayBuffer);
            resolve(new registerWebworker.TransferableResponse(arrayBuffer, [arrayBuffer]));
        };
    })})`

main.js
`this.wsWorker.postMessage({
            data: { fileName: this.fileName + '_' + frameIndex }
        })
            .then(res => {
                use res do something...
            })`

I hope you can tell me the reason for this problem, thank you very much！！！！

**Comment by kwolfy** [comment]
@liyunfei18
Hi. Sorry for delay. 
You are using it wrong way.

Sorry, your problem is not the library.

But i will try to help you.
Websockets are async and they doesnt guarantee order in the `onmessage` event. You should add unique identifier to each '.send' and return that identifier in their '.onmessage' response. So, then, you can resolve each postMessage depending on its unique identifier.
