### ISSUE TITLE
Promise is being rejected given message with value `null`

### ISSUE THREAD

**Issue by Gabisampaio** [kwolfy/webworker-promise#9]
The promise returned by `postMessage` seems to be rejected given a message with value`null`. I would expect the promise to be resolved, as the [`postMessage` API](https://html.spec.whatwg.org/multipage/web-messaging.html#dom-messageport-postmessage) allows sending messages with value `null`. 

### How to reproduce the issue?
I wrote a simple client of the library, which imports `WebworkerPromise` and posts a message with `null` value. The worker handler does nothing except returning the message received from the `main` thread. The promise is then rejected and we get an error in the `main` thread, captured with the `catch` clause.

**main.js**
```
const WebworkerPromise = require('webworker-promise');
const worker = new WebworkerPromise(new Worker('worker.js'));

worker
  .postMessage(null)
  .then((response) => {
  	console.log('MAIN: got response '+response);
    // handle response
  })
  .catch(error => {
  	console.log('MAIN: got error '+error);
    // handle error
  });
```

**worker.js**
```
const registerWebworker = require('webworker-promise/lib/register');

registerWebworker(
  (message, emit) => {
    return message;
  }
);
```

### How to fix?
The error originates in the function below, taken from **register.js**. When `o` has value `null` (which is exactly the case of the example shown above), we cannot access the `then` property without checking if `o` has value `null`. 
```
const isPromise = o => typeof o === 'object' && typeof o.then === 'function' && typeof o.catch === 'function';
```
Thus, checking if `o` is null before accessing the `then` property would solve the issue and avoid the promise to be rejected. We could then have the following instead:
```
const isPromise = o => typeof o === 'object' && o !== null && typeof o.then === 'function' && typeof o.catch === 'function';
```

**Comment by kwolfy** [comment]
Thank you. I would like yo see PR if have time
